# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

matrix:
  include:
    - name: "Linux tests"
      os: linux
      dist: trusty
      sudo: required

    - name: "macOS tests"
      os: osx
      #osx_image: xcode8
      #before_script: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

    - name: "Linux tests conditional Suggests"
      os: linux
      dist: trusty
      sudo: required
      env: _R_CHECK_DEPENDS_ONLY_=true

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) the newest QuantLib
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:edd/misc;
    fi
  - ./run.sh bootstrap

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./run.sh install_aptget r-cran-runit r-cran-zoo r-cran-timedate \
        r-cran-timeseries r-cran-tseries r-cran-chron r-cran-fts r-cran-tis;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./run.sh install_r RUnit zoo timeDate timeSeries tseries chron fts tis;
    fi

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

